name: Deploy to AWS EC2 using ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2Configurar AWS CLI. (Get credentials).
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      # 3Iniciar la instancia EC2
      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

      # 4 Obtener el ID de la cuenta de AWS, que luego es usado para hacer login en ECR
      - name: Get AWS Account ID
        id: aws_account
        run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      # 5 Loguearse en AWS ECR
      - name: Authenticate Docker with ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # 6 Construir la imagen Docker
      - name: Build Docker Image
        run: docker build --build-arg MODEL_PATH=model.pkl -t ${{ secrets.ECR_REPOSITORY }} .

      # 7 Etiquetar la imagen Docker para AWS ECR con :lastest
      - name: Tag Docker Image
        run: docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # 8 Subir la imagen a AWS ECR
      - name: Push Docker Image to ECR
        run: docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # 9 Conectarse a la instancia EC2 y ejecutar la nueva imagen. Comprobar que la instancia tenga los roles de SSM y acceso a ECR bien configurados y que la instancia tenga AWS CLI instalado.
      - name: Deploy Docker Container on EC2
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "[{\"Key\":\"instanceIds\",\"Values\":[\"${{ secrets.EC2_INSTANCE_ID }}\"]}]" \
            --parameters 'commands=[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com",
              "sudo docker stop scoring || true",
              "sudo docker rm scoring || true",
              "sudo docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest",
              "sudo docker run -d -p 80:8888 --name scoring ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"
            ]' \
            --query "Command.CommandId" \
            --output text \
            --region ${{ secrets.AWS_REGION }})

          echo "Waiting for command execution to complete..."

          # Revisar que el IAM User tenga ssm.ListCommandInvocations action permitida 
          
          while true; do
            STATUS=$(aws ssm list-command-invocations \
              --command-id "$COMMAND_ID" \
              --details \
              --query "CommandInvocations[0].Status" \
              --output text \
              --region ${{ secrets.AWS_REGION }})
              
            echo "Current status: $STATUS"
      
            if [[ "$STATUS" == "Success" ]]; then
                echo "Command execution completed successfully."
                break
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "TimedOut" ]]; then
                echo "Command execution failed!"
                exit 1
            fi
                echo "Still pending... checking again in 5 seconds."
                sleep 5
          done
            
      # 10 Obtener la IP pública de la instancia de EC2 y guardarla en las variables de entorno de Github Actions
      - name: Get EC2 Public IP
        id: get_ip
        run: |
          EC2_PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV

      # 11 Comprobar que el servicio corre sin problemas comprobando respuesta 200.
      - name: Check status code 200 on curl request 
        run: |
          STATUS_CODE=$(curl -X 'POST' 'http://$EC2_PUBLIC_IP:80/score1?data=https://github.com/jrodriguezru/ml-s/raw/refs/heads/main/data/score.csv' -H 'accept: application/json' -d '' -w "%{http_code}" -s -o /dev/null)
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "❌ Error: El servicio no respondió con código 200. Código recibido: $STATUS_CODE"
            exit 1
          fi
            echo "✅ El servicio respondió con código 200."

      # 12 Apagar la instancia EC2 después del despliegue
      - name: Stop EC2 Instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          aws ec2 wait instance-stopped --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
